set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR riscv64)
set(CMAKE_C_COMPILER riscv64-unknown-elf-gcc)
set(CMAKE_ASM_COMPILER riscv64-unknown-elf-gcc)
set(CMAKE_C_FLAGS_INIT "-march=rv64imac_zicsr_zifencei -mabi=lp64")
set(CMAKE_ASM_FLAGS_INIT "-march=rv64imac_zicsr_zifencei -mabi=lp64")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
